### ISSUE TITLE
0.15 issue checklist - READ before opening a new issue!

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1180]
As I'm sure you all know by now, Genisys has lots of issues with 0.15. Known issues are listed below.

- [x] [193a5c9] ~~Client-side crash when the player spawns in the vicinity of a mob or the player spawns a mob.~~

- [x] [193a5c9] ~~Players are connected to all mobs in the area (including other players) by leashes.~~ (not completely fixed)

- [ ] **Mobs in mob spawners have leashes attached which are constantly flailing around**

- [x] Various issues with custom mob plugins such as FNPC and Slapper, including leashes and client-side crashes. Apparently these issues have been resolved with updates to these plugins, please make sure your plugins are up to date.

- [x] [193a5c9] ~~Block updates are not sent to the client (explains issue #1178)~~

- [x] [4bf731c] ~~Batch block updates do not work properly. This causes issues with world editing plugins as only some of the changes are visible to clients unless they re-login.~~ (MCPE bug?)

- [x] [193a5c9] ~~Players' movements cannot be seen by other players. Actions such as swinging a sword are however visible.~~

- [x] [919a195] ~~Weather issues: rain/snow still happen even when weather is disabled in the configuration.~~

- [x] [7dd3afc] ~~Skins: Player skins always using the Alex model~~

- [x] Clients will crash in the vicinity of unknown blocks, i.e. blocks which are not currently in PE. This is an MCPE bug and as such is not the fault of Genisys.

- [ ] Enchanted arrows crash the client. Why arrows are able to be enchanted at all I'm not entirely sure, but this needs to be corrected.

Please comment below if you experience any issues not described here.

**Comment by kabluinc** [comment]
when I spawn in my spawn, the floor is all covered in snow. after travelling some distance and coming back to spawn, the snow disappears and the land is back to normal. some biome/map issues? 

never happened with 0.14.3 and when the map is put in a 0.14 server there's no such issues

**Comment by evolvedtm** [comment]
Although its a bit buggy, thank you for updating

**Comment by dktapps** [comment]
@evolvedtm you mean a _lot_ buggy. We're working on it.

**Comment by kaitododoyt** [comment]
weather doesn't work

**Comment by evolvedtm** [comment]
Well, either way, I appreciate it @dktapps

**Comment by kabluinc** [comment]
Weather has always been off from genisys.yml for my server but after update to 0.15 its snowing!? But on genisys.yml weather is still false

**Comment by Tolo0** [comment]
I think the main bugs is the leads and not being able to see players move.

**Comment by kabluinc** [comment]
another bug iv found is that when a folder e.g. players folder is deleted, the server does not automatically recreate the folder. this error was shown in console. 

Warning: file_put_contents(C:\Users\Gamer27832 server\Desktop\0.15 testing\players/ssundee.dat): failed to open stream: No such file or directory in C:\Users\Gamer27832 server\Desktop\0.15 testing\src\pocketmine\Server.php on line 1016

Warning: file_put_contents(C:\Users\Gamer27832 server\Desktop\0.15 testing\players/ssundee.dat): failed to open stream: No such file or directory in C:\Users\Gamer27832 server\Desktop\0.15 testing\src\pocketmine\scheduler\FileWriteTask.php on line 38

**Comment by biswarm22** [comment]
I removed all the mobs, but the client still crashes on join

**Comment by Adam1609** [comment]
It work, but still custom alert and my npc plugin has error.

**Comment by dktapps** [comment]
@Adam1609 API changes. Plugins will need to be updated.

**Comment by SuperDude36** [comment]
How the heck do you even download it? I don't want to move to ImagicalMine because Genisys is way better and ImagicalMine is discontinued. Please add the branch again and please put a release with phar download.

**Comment by dktapps** [comment]
@SuperDude36 use Jenkins. Links are in the README.md

**Comment by Muqsit** [comment]
@SuperDude36 http://github.com/Muqsit/Genisys has leads bug fixed. I've made a PR already but if you want to rush, you can go to that link and download my fork!

**Comment by kabluinc** [comment]
So almost everything is working for me now even slappers/NPCs are working and nothing crashes however my whole server is snowing.

Weather is set to off in genisys.yml but its continuously snowing even if I do /weather clear

**Comment by Muqsit** [comment]
Leash bug fixed

**Comment by XxDXM-hippiexX** [comment]
So I can't connect to the server from a outside Network as if it's not binding to the port. I'm on Windows 10 and it doesn't do this if I downgraded to a version below the 0.15 .0 update.

**Comment by LCraftPE** [comment]
There is no protection in 0.15.. Plugin of protection doesn't wok in 0.15.0...

**Comment by dktapps** [comment]
@LCraftPE Known issue. If you would like to try the 0.15-bugfixes branch that contains fixes for this and other issues.
@XxDXM-hippiexX Are you using Win10 edition on the same machine that you're running the server on? If so then it's believed to be a Win10 edition bug.

**Comment by XxDXM-hippiexX** [comment]
@dktapps Im not sure what you are talking about..the pc is windows 10 yes and that is what the server is running on. I dont have this issue on older versions of genisus though.

**Comment by MCPEPluginer16** [comment]
How i do Fixed Spawn Crash i removed all mobs and Disabled mobgenerte in genisys.yml

**Comment by dktapps** [comment]
@MCPEPluginer16 you can use ClearLagg to remove all entities. Optionally you could use a build from the 0.15-bugfix branch which has this issue resolved.

**Comment by MCPEPluginer16** [comment]
Used it but i Jenkenis Work ?

**Comment by MCPEPluginer16** [comment]
it*

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/1866086/artifacts/download

**Comment by MCPEPluginer16** [comment]
Don't worked crashed me agin

**Comment by dktapps** [comment]
@MCPEPluginer16 If you use any custom mob plugins such as FNPC or Slapper then I recommend you remove them for now.

**Comment by MCPEPluginer16** [comment]
0 Plugins

**Comment by XxDXM-hippiexX** [comment]
@dktapps Did you reference my issue as the spawn crash?..cuz thats not it. lol

**Comment by MCPEPluginer16** [comment]
Yes ny issue like this^

**Comment by XxDXM-hippiexX** [comment]
@dktapps sorry dont mind me..tech noob passing threw! XD i just reset my modem and it works now..my servers been down for days and for some reason thats all i had to do.

**Comment by ishitatsuyuki** [comment]
The PR have been merged. Can you confirm which of these is fixed?
@dktapps

**Comment by dktapps** [comment]
@ishitatsuyuki I'll update the list in a minute.

**Comment by dktapps** [comment]
@XxDXM-hippiexX no problem, don't worry about it. @ishitatsuyuki I've updated the checklist.

**Comment by Muqsit** [comment]
Can someone verify whether there's an issue with PlayerMove? PlayerMove packet isn't sent to other clients so players appear as statues to other players even tho they are actually moving.

**Comment by dktapps** [comment]
@Muqsit I believe this is resolved in the latest build. Unless MCPE had a sneaky auto-update overnight

**Comment by kabluinc** [comment]
After 0.15 I think floating text particles have stopped working because any floating text are invisible to the player. This issue was opened in the pocketmine repository too but not resolved.

**Comment by XxDXM-hippiexX** [comment]
I have had the skin issue though..not sure if its the same one as reported but everyone had my skin.

**Comment by SirOptic** [comment]
When teleporting to old maps the server closes...

**Comment by ishitatsuyuki** [comment]
@SirOptic stop spamming with your outdated version.

**Comment by SirOptic** [comment]
By the way when is the creative invinventory going to update

**Comment by Guillaume351** [comment]
Mobs nametag and floating text does not show too (for mobs,they show only if you less than 1 block from the mob and turn the camera in a certain angle), not sure it is a server-side issue :/

**Comment by ABAxStorm** [comment]
The leash issue actually doesn't bother me, because the other bugs were fixed :P

**Comment by CLiu13** [comment]
The client crashing due to being next to non-PE blocks can be fixed by converting maps with pmimporter by Aliuly, using the dev branch.

**Comment by MCPEPluginer16** [comment]
@CLiu13 How?

**Comment by CLiu13** [comment]
Use the version found here: https://github.com/Muirfield/pmimporter/tree/dev and carefully read the documentation at the bottom.

**Comment by intagaming** [comment]
You guys sure that leashes were fixed? I'm using 479 and still have no changes.

**Comment by ishitatsuyuki** [comment]
It has already mentioned that it's not completely fixed.

**Comment by intagaming** [comment]
Just asking cause there's no any comment about that.

**Comment by ABAxStorm** [comment]
Confirmed that leads are a slapper issue. Slapper updated on their GitHub with a fix for this.

**Comment by biswarm22** [comment]
####   Temp fix for crashes related to unsupported blocks
BEFORE: Backup your world before doing this in case anything happens 
1. Download latest satble build of MCedit here: http://www.mcedit.net/downloads.html
2. Install MCEDIT
3. Open Mcedit and import your world in
4. Copy your world and paste it into a blank MCPE world
5. Copy and paste from the MCPE world to Anvil world.
6. Save the anvil world
NOTE: This may make your signs disappear and will replace non MCPE blocks with another block such as white wool

**Comment by linuzo** [comment]
pmimport works fine for updating unknown blocks it replaces unknown blocks with a trapdoor!

**Comment by kaitododoyt** [comment]
I have problems with this function:

foreach ($tiles as $tile) {
                                                                        if ($tile instanceof Sign) {
                                                                            $text = $tile->getText();
                                                                            if (strtolower($text[0]) == "runner") {
                                                                                $levelArena->setBlock($tile->add(0, 2, 0), new Air());
                                                                                $levelArena->setBlock($tile->add(0, 3, 0), new Air());
                                                                            }
                                                                        }
                                                                    }

Only some blocks are updated, this function works fine in 0.14.3

**Comment by Muqsit** [comment]
I can confirm the setBlock issue

**Comment by KairusDarkSeeker** [comment]
1 question, why cant i hit players even im in Survival/Adventure Mode?

**Comment by daniktheboss** [comment]
Hey nooby question but how can I disable the hud on screen? It shows my cordinates and when somone joins it says welcome @player! How can I disable that? Thanks

**Comment by Muqsit** [comment]
@daniktheboss GENISYS has no kind of HUD. To disable the Welcome @player, leave the message field blank (" ")

**Comment by daniktheboss** [comment]
Ok how about the coordinates?

**Comment by dktapps** [comment]
There have been changes to the UpdateBlockPacket, which mean that block updates cannot be sent in batches. This causes issues with world editing plugins and the problem @kaitododoyt mentioned. If you log out and log back in the changed blocks will be visible. I'm working on a fix for this.

**Comment by dktapps** [comment]
@kaitododoyt To send block updates directly instead of in batches, you can try calling setBlock with the `$direct` parameter as `true`, which will bypass the batch sending, like this:
```
$levelArena->setBlock($tile->add(0, 2, 0), new Air(), true);
```
This may cause heavy lag on the client-side, I do not know.

**Comment by SleepSpace9** [comment]
Team ClearSky has a fix for damage showing up when an EntityDamageEvent is cancelled => https://github.com/ClearSkyTeam/ClearSky/commit/891b63ac4d038a3a6c2a8f445e487779885bed5e
Maybe Genisys can use that too (if ClearSky don't mind - @robske110  ?)

**Comment by Guillaume351** [comment]
@SleepSpace9 Just tried that on my Genysis, works ! :) (except when you take fall damages, you still see the animation on you)

**Comment by robske110** [comment]
Of course we don't mind :)

**Comment by SzczepanPolska** [comment]
Probles :/
Video
[

![image](https://cloud.githubusercontent.com/assets/16169053/16207107/c2a6237e-372b-11e6-9541-fceca9afc420.gif)

](url)

**Comment by robske110** [comment]
That is related to the crash if unknown blocks are there

**Comment by xHFx** [comment]
How do we fix disabling weather and disabling mob spawning doesnt work either

**Comment by PeratX** [comment]
Weather issue may related to the chunk's temperature

**Comment by legoboy0215** [comment]
@Guillaume351 Like on my issue? https://github.com/iTXTech/Genisys/issues/1235

**Comment by EnderKenji** [comment]
Find some fixes from [Jack's Steadfast2](https://github.com/JackNoordhuis/Steadfast2) ?

**Comment by dktapps** [comment]
That patch causes players not to be able to attack one another full-stop, as opposed to only in selected non-PvP areas.

**Comment by robske110** [comment]
Batch block updates do not work properly. This causes issues with world editing plugins as only some of the changes are visible to clients unless they re-login. (MCPE bug?)
->I 'hacked' this here: https://github.com/ClearSkyTeam/ClearSky/commit/bec1a7b854c04502dac242f507c3f869a5000555
Maybe we should add sth in pocketmine.yml/whateverconfigfile to let the user choose to either overload (DDOS the clients) the network with that or random blocks stuck around.

**Comment by SleepSpace9** [comment]
> That patch causes players not to be able to attack one another full-stop, as opposed to only in selected non-PvP areas.

@dktapps do you mean the patch for https://github.com/iTXTech/Genisys/issues/1235 (Hurt animation even though even is cancelled) ?
On my Genisys server all is working fine with this fix in Player.php . (damage animation in PVP areas and no anmiation in non-PVP areas + human Slapper entities)

**Comment by dktapps** [comment]
@SleepSpace9 yes. I tried it and it caused the problems I mentioned above.

**Comment by SleepSpace9** [comment]
Sorry for spamming, maybe there's a misunderstandig - I used the fix from ClearSky (https://github.com/ClearSkyTeam/ClearSky/commit/891b63ac4d038a3a6c2a8f445e487779885bed5e), not from Steadfast which Legoboy mentioned in the issue description of https://github.com/iTXTech/Genisys/issues/1235.

**Comment by alexbgameson** [comment]
Do you expect MCPE to fix the unsupported blocks bug in the next update?

**Comment by dktapps** [comment]
@alexbgameson I'm not optimistic, no

**Comment by OlegTheGeek** [comment]
Oh How do I fix slapper plugin , so it won't crash client?

**Comment by jojoe77777** [comment]
@OlegTheGeek I'll do that.

I think I found the cause for nametags not showing on entities (yes I know it's not in this list) : https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/Player.php#L1427-L1429

**Comment by EnderKenji** [comment]
Hopefully add 0.15.0 items into creative inventory. Thanks iTX

**Comment by XxDXM-hippiexX** [comment]
setMotion() broke?

**Comment by TheProest35YT** [comment]
ImagicalMine is Reactive
On Github @SuperDude36 
https://github.com/Inactive-to-Reactive/ImagicalMine

**Comment by Driesboy** [comment]
remove it or you will banned

**Comment by dktapps** [comment]
@Driesboy XD
@SuperDude36 oh boy you definitely are asking to be banned by posting that round here

**Comment by robske110** [comment]
i literraly was on this site while you commented

**Comment by legoboy0215** [comment]
Same. Now delete all our messages.

**Comment by dktapps** [comment]
XD

**Comment by robske110** [comment]
Will do in some secs

**Comment by robske110** [comment]
MASS DELETE

**Comment by dktapps** [comment]
really?

**Comment by robske110** [comment]
And I'm in school :P

**Comment by legoboy0215** [comment]
lol I was on this issue.

**Comment by robske110** [comment]
why disliked by legoboy?

**Comment by legoboy0215** [comment]
lol You aren't supposed to do that in school :P

**Comment by robske110** [comment]
What?

**Comment by TheProest35YT** [comment]
Why do i have errors deleting

**Comment by xHFx** [comment]
Any plans on fixing the MobAI

**Comment by Tolo0** [comment]
Anyone having problems with pc maps? everytime I tp to one. I crash.

**Comment by robske110** [comment]
Problem with unknown blocks crashing the client

**Comment by House-Kitty-Mew** [comment]
I get this error while trying to craft on GearVR version
Notice: Undefined offset: 0 in phar:///srv/genisys/genisys.phar/src/pocketmine/Player.php on line 3494

**Comment by CubeFromSpace** [comment]
@dktapps I think there is a Boolean (true/false) value for leash rendering. Otherwise I might not be able to help you.

**Comment by ChavoJoker** [comment]
@kabluinc I still get that Issue where the floor is covered in snow. I even tried taking it away and when I re join it is still there. After so many updates recently I thought it would be fixed by now :(

**Comment by kabluinc** [comment]
@ChavoJoker i found a fix for that. go to one corner of the snowy world and type /biome pos1. go on the opposite corner so that it covers all the snowy area then type /biome pos2 and then /biome set 1. restart the server and all snow will be gone.

**Comment by Muqsit** [comment]
Wait, player crashes still occur. Why is it ticked?

**Comment by ChavoJoker** [comment]
@kabluinc wow that worked thanks!! Thumbs up for you! :D Ima test that biome command too

**Comment by ChavoJoker** [comment]
@CLiu13 @biswarm22 @robske110 I have found another solution to fix unknown blocks crashing the client which I posted under issue #1256

**Comment by Tolo0** [comment]
found a bug. enchanted arrows make the client crash. and the client's inventory or player profile has to be reset to fix it. they could be other items that do this also.

**Comment by dktapps** [comment]
Tipped arrows aren't supported, hence why they haven't been added.

**Comment by Tolo0** [comment]
I didn't say tipped arrows. just normal enchanted arrows. enchat one and u will see. do
/enchant name 1 5
while holding a arrow.

**Comment by dktapps** [comment]
You can't enchant arrows in vanilla. Duh. Unsupported feature.

**Comment by Tolo0** [comment]
u can enchant any item in the game.

**Comment by ishitatsuyuki** [comment]
@Tolo0 no, you can't. See http://minecraft.gamepedia.com/Commands#enchant

**Comment by dktapps** [comment]
You can't enchant arrows **in vanilla**. Should I make it any plainer?

**Comment by Tolo0** [comment]
why talk about vanilla? I was reporting a bug that's it lol.

**Comment by Tolo0** [comment]
@ishitatsuyuki ur missing the point. I didn't say enchanting a arrow would give the arrow the ability to use the enchanted effect. That's not the case. I'm reporting that arrows when enchanted make the client crash. and maybe other items when enchanted.

**Comment by dktapps** [comment]
@Tolo0 **enchanted arrows are not vanilla, therefore they are not a supported feature.**

**Comment by CubeFromSpace** [comment]
I actually think that enchanted arrows are vanilla, as there are enchantments, arrows, and plugins on the server and on Minecraft PE. (And plugins are technically not vanilla though)

**Comment by CubeFromSpace** [comment]
Edit 2: @ishitatsuyuki that applies only to Minecraft on the PC. PC plugins are closely tied to PC's internal programs. Jeb said himself.

**Comment by Tolo0** [comment]
@dktapps so it's a glitch then? becos they can be enchanted. do I need to make a video to show u guys?

**Comment by CubeFromSpace** [comment]
No, its just possible in Minecraft PE, but not openly developed by Mojang

**Comment by dktapps** [comment]
Client crash = client bug. However it can't be reported because there's no way to obtain enchanted arrows without mods or 3rd party software such as Genisys. This is not Genisys' fault.

**Comment by CubeFromSpace** [comment]
@dktapps probably right, Genisys is based on Pocketmine

**Comment by Tolo0** [comment]
isn't they away genisys can stop items like arrows, sticks, blocks. basically stop all unsupported items from being enchanted with the enchant command? that would solve the problem. and stop players crashing.

**Comment by CubeFromSpace** [comment]
good idea :) but maybe it would save CPU to just remove the command altogether

**Comment by robske110** [comment]
You can't just say client crashes are client's fault. It is our fault, we do either send total nonsense or just send old stuff that has been changed. Enchanting arrows with the enchant cmd makes the client crash. It IS our fault because WE told the computer TO accept a item from the USER to enchant, regardless if it can be enchanted or not. So we for example simply implement an array $canBeEntchantedIDs = [93,264,3,6,246,24,63,4,57642,,72,347,62,46,452,6,,] you know what i mean

**Comment by dktapps** [comment]
@robske110 Client doesn't expect arrows to be enchanted.

**Comment by robske110** [comment]
yes that's exactly what i mean

**Comment by robske110** [comment]
So just check what can be enchanted before sending random stuff to the client

**Comment by Tolo0** [comment]
@dktapps majority of players that play minecraft are kids. so that's like telling a kid to not press the big red button. when u know they will lol. kids always do what isn't ment to be done.

**Comment by dktapps** [comment]
@Tolo0 lol you make a good point.

**Comment by robske110** [comment]
And @dktapps I think it's time to separate 0.15 issues into single ones

**Comment by robske110** [comment]
The most are resolved

**Comment by CubeFromSpace** [comment]
What about enchanting tables and anvils? Would $canbeenchanted apply to it too? (PS. Sorry about the spam part)

**Comment by House-Kitty-Mew** [comment]
I get this error while trying to craft on GearVR version
Notice: Undefined offset: 0 in phar:///srv/genisys/genisys.phar/src/pocketmine/Player.php on line 3494

**Comment by dktapps** [comment]
Gear VR is not directly supported. This is most likely the same problem as Win10 Edition with crafting. Refer to #1337 to track progress.

**Comment by CubeFromSpace** [comment]
@dktapps is right, Gear VR is technically part of Win10, and they would likely share the same problems

**Comment by dktapps** [comment]
@CubeFromSpace Gear VR part of Win10? _What_?

I was actually meaning that it's due to the similarity in crafting GUI.

**Comment by shmoosey** [comment]
Uhh... There aren't any mobs spawning in my world (0.15.4), and when spawned in with "/summon", they seem not to have any AI.

**Comment by KairusDarkSeeker** [comment]
[ ] Signs gets dropped when placed on a wall :p

**Comment by CubeFromSpace** [comment]
Lol what I said last month: I meant VR and not WIN10

**Comment by KairusDarkSeeker** [comment]
[LBCSpleef](https://github.com/KairusDarkSeeker/LBCSpleef)

**Comment by legoboy0215** [comment]
Please don't go off-topic.
